export const REPORT_PAGE_TITLES = [
  { icon: "📘", title: "Cover" },
  { icon: "💌", title: "A letter to parents" },
  { icon: "👧", title: "Student profile & birth details" },
  { icon: "🪐", title: "Birth chart (Lagna Kundali)" },
  { icon: "📋", title: "Planetary positions" },
  { icon: "🌙", title: "Moon sign & Nakshatra" },
  { icon: "🌅", title: "Lagna: personality" },
  { icon: "🔥", title: "Temperament & elements" },
  { icon: "🧠", title: "Intelligence & learning style" },
  { icon: "🏫", title: "Education indicators" },
  { icon: "🧭", title: "Recommended stream" },
  { icon: "🏆", title: "10th house: career analysis" },
  { icon: "📈", title: "Top career fields ranked" },
  { icon: "🎯", title: "Best-fit careers in detail" },
  { icon: "🚦", title: "Fields needing care" },
  { icon: "💪", title: "Strengths & natural talents" },
  { icon: "🌱", title: "Challenges & parent support" },
  { icon: "⏳", title: "Vimshottari Dasha timeline" },
  { icon: "📅", title: "Key periods for studies" },
  { icon: "✋", title: "Palmistry observations" },
  { icon: "🙂", title: "Face reading & case study" },
  { icon: "🪔", title: "Remedies & parent action plan" },
] as const;
